- question: Що включає в себе поняття "інформаційна гігієна"?
  answers:
   - Вплив на організм людини та суспільне здоров'я інформаційних потоків, що надходять до людини.
   - Система, призначена для одержання, обробки, зберігання, відображення та/або реєстрації даних
   - Нову історичну фазу розвитку суспільства
- question: Несвідома неправда, коли вас не хотіли вводити в оману. Просто помилка.
  answers:
   - Disinformation
   - Misinformation
   - Malinformation
- question: Яке з наведених визначень найточніше описує термін "фейкова новина"?
  answers:
    - Спотворена або вигадана інформація, яка свідомо подається як справжня новина.
    - Інформація, яку поширюють без комерційної вигоди.
    - Офіційне повідомлення від державного органу.

- question: Що є основною метою дезінформації?
  answers:
    - Навмисне введення в оману для досягнення певних цілей.
    - Поширення правдивих фактів без контексту.
    - Помилкове інформування через незнання автора.

- question: Як називається явище, коли людина шукає та сприймає лише ту інформацію, яка підтверджує її погляди?
  answers:
    - Ехо-камера
    - Цензура
    - Критичне мислення